name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - run: docker pull registry.gitlab.com/4tu/spheal
    - run: mkdir build
    - run: docker build -t builder .
    - working-directory: ${{ github.workspace }}/build
      shell: cmd
      run: |
        docker run --name 3ds builder /bin/bash -c "make -f Makefile.3ds"
        docker run --name wii builder /bin/bash -c "make -f Makefile.wii"
        docker run --name wiiu builder /bin/bash -c "make -f Makefile.wiiu"
        docker run --name switch builder /bin/bash -c "make -f Makefile.switch"
        docker cp 3ds:/code/hb-appstore/appstore.3dsx appstore.3dsx
        docker cp wii:/code/hb-appstore/appstore.dol appstore.dol
        docker cp wiiu:/code/hb-appstore/appstore.rpx appstore.rpx
        docker cp switch:/code/hb-appstore/appstore.nro appstore.nro
    - uses: actions/upload-artifact@v2.2.4
      with: 
        name: Binaries
        path: ${{ github.workspace }}/build
